import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import ShoppingCartModal from './components/ShoppingCartModal'
import { Toaster } from 'react-hot-toast'

const vazir = Vazirmatn({ 
  subsets: ['arabic'],
  weight: "600",
  variable: "--font-vazir"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={`${vazir.variable} font-vazir`}>
        <Navbar />
        <ShoppingCartModal />
        <Toaster />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
